@startuml
!pragma layout smetana




:Kunde:
:Autovermietung: as AV



(Fahrzeugaufnahme) as (FA)
(Fahrzeugübersicht) as (FÜ)
(Vorbestellen)
(Leihen)
(Rückgabe)



AV--FA
AV--FÜ
Kunde--Vorbestellen
Kunde--Leihen
Kunde--Rückgabe
AV--Leihen
AV--Rückgabe



(Rückgabe)..>Leihen : <<include>>
(Vorbestellen)..>Leihen : <<extend>>



@endumlto
@startuml



:Kunde:
:Autovermietung: as AV
:Premiumkunde: as PK



(Fahrzeugaufnahme) as (FA)
(Fahrzeugübersicht) as (FÜ)
(Vorbestellen)
(Leihen)
(Rückgabe)
(Nachtschalter)
(Tanken)



AV--FA
AV--FÜ
Kunde---Vorbestellen
Kunde--Leihen
Kunde---Rückgabe
Kunde--Tanken
AV---Leihen
AV---Rückgabe
PK--Nachtschalter



(Rückgabe)-->Leihen : <<include>>
(Vorbestellen)-->Leihen : <<extend>>
(Nachtschalter)-|>Rückgabe : <<inherit>>
PK-|>Kunde: <<inherit>>
Tanken-->(Rückgabe) : <<include>>




@endumlto